export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CREATE_BOOKING = 'CREATE_BOOKING';
export const FETCH_BOOKINGS = 'FETCH_BOOKINGS';
export const FETCH_BOOKING = 'FETCH_BOOKING';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const EDIT_BOOKING = 'EDIT_BOOKING';

export const FETCH_USER = 'FETCH_USER';
export const CREATE_USER_RESERVATION = 'CREATE_USER_RESERVATION';
export const FETCH_USER_RESERVATIONS = 'FETCH_USER_RESERVATIONS';